[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

[[redirects]]
  from = "/archive/*"
  to = "/.netlify/functions/proxy/archive/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
